class UserAlreadyExistsError(Exception):
    """Se lanza cuando se intenta registrar un usuario que ya existe."""
    pass